# Generated by Django 5.2 on 2026-04-30 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_templates', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailtemplate',
            name='trigger_key',
        ),
        migrations.CreateModel(
            name='ProjectEmailAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action_key', models.CharField(choices=[('created', 'Project Created'), ('updated', 'Project Updated'), ('status_changed', 'Status Changed'), ('deleted', 'Project Deleted')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_actions', to='projects.externalproject')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_actions', to='email_templates.emailtemplate')),
            ],
            options={
                'ordering': ['project__name', 'action_key'],
                'unique_together': {('project', 'action_key')},
            },
        ),
    ]
