# Generated by Django 5.2 on 2026-04-30 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulepermission',
            name='module',
            field=models.CharField(choices=[('users', 'User Management'), ('roles', 'Roles & Permissions'), ('audit', 'Audit Log'), ('projects', 'External Projects'), ('email_templates', 'Email Templates'), ('settings', 'System Settings')], max_length=50),
        ),
        migrations.AlterField(
            model_name='userpermissionoverride',
            name='module',
            field=models.CharField(choices=[('users', 'User Management'), ('roles', 'Roles & Permissions'), ('audit', 'Audit Log'), ('projects', 'External Projects'), ('email_templates', 'Email Templates'), ('settings', 'System Settings')], max_length=50),
        ),
        migrations.CreateModel(
            name='ProjectPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('can_view', models.BooleanField(default=False)),
                ('can_create', models.BooleanField(default=False)),
                ('can_edit', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='projects.externalproject')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_permissions', to='roles.role')),
            ],
            options={
                'ordering': ['project__name'],
                'unique_together': {('role', 'project')},
            },
        ),
    ]
