# Generated by Django 5.2 on 2026-05-01 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("approvals", "0002_projectapprovalconfig"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="workflowinstance",
            new_name="approvals_w_content_924174_idx",
            old_name="approvals_w_content_idx",
        ),
        migrations.RenameIndex(
            model_name="workflowinstance",
            new_name="approvals_w_status_564549_idx",
            old_name="approvals_w_status_idx",
        ),
    ]
