# Generated by Django 5.2 on 2026-07-02 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "approvals",
            "0003_rename_approvals_w_content_idx_approvals_w_content_924174_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="workflowstepinstance",
            name="deadline_handled",
            field=models.BooleanField(default=False),
        ),
    ]
